# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 06:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chocolate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Chocolate Name')),
                ('details', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Chocolate Description')),
                ('price', models.IntegerField(blank=True, help_text='5 digits maximum', null=True, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(0)], verbose_name='Chocolate Price')),
                ('manufacture', models.CharField(max_length=100, unique=True, verbose_name='Chocolate Manufacture')),
            ],
        ),
    ]
